# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

stages:
  - build
  - test
  - deploy

code_analyze:
  image: cirrusci/flutter
  stage: test
  needs: []
  script:
    - mv lib/src/ffi.dart lib/src/ffi.txt
    - flutter format . --set-exit-if-changed
    - mv lib/src/ffi.txt lib/src/ffi.dart
    - flutter analyze

build_js:
  image: archlinux:latest
  stage: build
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S emscripten libxml2 make cmake jq
    - source /etc/profile
    - useradd -m build
    - chown -R build .
    - su -c 'make -C js' build
  artifacts:
    paths:
      - js/Imaging.js
      - js/Imaging.wasm

test_js:
  image: archlinux:latest
  stage: test
  needs:
    - build_js
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S chromium dart
    - source /etc/profile
    - useradd -m test
    - chown -R test .
    - su -c 'pub get' test
    - su -c 'pub run test -p chrome' test

test_native:
  image: archlinux:latest
  stage: test
  needs: []
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S dart binutils gcc make cmake
    - source /etc/profile
    - useradd -m test
    - chown -R test .
    - su -c ./scripts/prepare.sh test
    - su -c 'pub get' test
    - su -c 'LD_LIBRARY_PATH=$(pwd)/build pub run test' test
    - su -c 'LD_LIBRARY_PATH=$(pwd)/build dart example/example.dart' test

pages:
  stage: deploy
  needs: []
  image: cirrusci/flutter
  script:
    - ./scripts/doc.sh
    - mv doc/api public
  artifacts:
    paths:
      - public
  only:
    - master
