# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: native_imaging
version: 0.0.2
description: Dart bindings for Imaging from Pillow with jpeg and blurhash encoders
homepage: https://famedly.gitlab.io/libraries/native_imaging/
repository: https://gitlab.com/famedly/libraries/native_imaging

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  js: ^0.6.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_imaging
        pluginClass: NativeImagingPlugin
      ios:
        pluginClass: NativeImagingPlugin
